### ISSUE TITLE
Demo doesn't seem to be working - Github Pages 404

### ISSUE THREAD

**Issue by osdiab** [quietshu/apple-pencil-safari-api-test#1]
Your Github page is returning a 404, presumably the HTML has a markup issue in it and Github is not displaying the page as a result - tried replacing the body of the site with `<h1>Hello World</h1>` on my fork and it no longer shows a 404 after that, for your info - thanks for putting this demo together by the way!

**Comment by osdiab** [comment]
Yep it was the script - when I removed it it loaded (but did nothing obviously)

I threw it into a separate file and removed the bad array iterations on my  branch and it works there, will leave that as a PR on here if you want it lol

**Comment by shuding** [comment]
Thanks for the help :D
